# Generated by Django 2.2.6 on 2019-10-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20170511_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('no', 'show')},
        ),
    ]
